@extends('layouts.master')
@section('title','Sorted Transaction Purchase Requests')

@section('extra-css')
    {{-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/skins/all.css"> --}}
    <link rel="stylesheet" href="{{ URL::to('/vendors/pretty-checkbox.min.css') }}">
    <style>
        h1.header-title{
            text-transform: uppercase;
            font-weight: bold;
            letter-spacing: -2px;
        }
        /* List Group*/
        .list-group-item:hover{
            background: #eee;
            cursor: pointer;
        }
        .list-group-item:hover .buttons, table tbody tr:hover .row-buttons{
            display: block;
        }
        .list-group-item-heading{
            font-size: 150%;

        }
        .list-group-item-text{
            color: #999;
        }
        .panel-footer small .modal-footer {
            color: #999;
        }

        /*Task Modal */

        input.task-input{
            width: 50%;
            border: none;
            font-size: 18px;
            height: 46px ;
            line-height: 1.3333;
            color: #555;
            display: block;
            font-size: italic;

        }
        input.task-input:focus, input.task-input:active{
            outline: none;
        }
        .done{
            text-decoration: line-through;
            color: #ddd;
        }
        table.table tbody tr td{
            padding-top: 15px;

        }
        .task-item-title{
            position: relative;
        }
        .hidden{
            display: none;
        }
        .task-label{
            background-color: #8a6d3b !important;
            padding: 7px !important;
            font-size: 13px !important;
            font-weight: 300 !important;
        }
        .buttonload {
            background-color: #4CAF50; /* Green background */
            border: none; /* Remove borders */
            color: white; /* White text */
            padding: 12px 24px; /* Some padding */
            font-size: 16px; /* Set a font-size */
        }
        #active-tasks-counter{
            font-size: 14px;
            background-color: #ff4f4a;
            color: #fff; padding: 5px; 
        }
        #loading-on{ display:none; }
        .modal-perusu {
          width: 75%;
          margin: auto;
        }
    </style>
@endsection

@section('content')

<div id="page-wrapper">
    <div class="row">
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header" style="padding-left: 10px">
                    <div class="navbar-text navbar-brand-centered"><h4>Fresh Inventory</h4></div>
                </div>
            </div>
        </nav>
        @if(Session::has('updated_status'))
            <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                {{ Session::get('updated_status') }}
            </div>
        @endif
    </div>

    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">Sorted Transaction Purchase Request(s)</div>
            <div class="panel-body">
                <div>
                    <table id="transactions_sorted_table" class="table table-hover table-bordered table-responsive" style="width:100%"></table>
                </div>
                @include('inventory-management.sorted-items.confirmmodal')
                @include('inventory-management.sorted-items.taskmodal')
            </div>
            <div class="panel-footer"></div>
        </div>
    </div>
</div>

@endsection

@section('extra-js')
    {{-- <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.18.0/axios.min.js"></script> --}}
    {{-- <script src="https://cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/icheck.min.js"></script> --}}
    <script>
        (function(){
            // DataTable Sorted Listing
            $('#transactions_sorted_table').DataTable({
                "processing": true,
                "serverSide": true,
                "ajax": "/warehouse/sorted/transactions",
                "columnDefs": [ { //this prevents errors if the data is null
                    "targets": "_all",
                    "defaultContent": ""
                } ],
                "language": {
                    "search": "Search Records: "
                },
                "order": [[0,'desc']],
                "columns": [
                    {data: 'batch_no', title: 'SORTED BATCH NUMBER', orderable: true, searchable: true, 'className' : 'text-center', "width": "20%"},
                    {data: 'created_by', title: 'GENERATED BY', orderable: true, searchable: true, 'className' : 'text-center', "width": "20%"},
                    {data: 'created_at', title: 'GENERATED AT', orderable: false, searchable: false, 'className' : 'text-center', "width": "20%"},
                    {data: 'action', title: 'ACTION', orderable: false, searchable: false, 'className' : 'text-center'}
                ],
                "buttons": [
                    'pdf'
                ]
            });

            // Show and add task of Todo List
            $('body').on('click','.show-task-modal',function(event){
                event.preventDefault();

                var anchor = $(this),
                    url = anchor.attr('href'),
                    title = anchor.data('title'),
                    action = anchor.data('action'),
                    parent =anchor.closest('.list-group-item');

                $('#task-modal-subtitle').text(title);
                $('#task-form').attr('action',action);
                $('#selected-todo-list').val(parent.attr('id'));

                $.ajax({
                    url:url,
                    datatype:'html',
                    beforeSend: function(){
                        $("#loading-on-"+ title).show();
                    },
                    success:function (response) {
                        $('#task-table-body').html(response);
                        $("#loading-on-"+ title).hide();
                        // initIcheck();
                        // countActiveTasks();
                        $('#task-modal').modal('show');
                    }
                });
            });

            // function countAllTasksOfSelectedList() {
            //     var total = $('#task-table-body tr').length,
            //         selectedTodoListId = $('#selected-todo-list').val();

            //     $('#'+selectedTodoListId).find('span.badge').text(total +" "+ (total >1 ? 'tasks' : 'task'));
            // }

            // function countActiveTasks() {
            //     var total = $('tr.task-item:not(:has(td.done))').length;
            //     $('#active-tasks-counter').text(total +" "+(total > 1 ? ' tasks' : ' task') + " left");
            // }

            // Update mark of Task
            // function markTheTask(checkbox) {

            //     var url = checkbox.data('url'),
            //         completed = checkbox.is(":checked");

            //     $.ajax({
            //         url : url,
            //         type : 'PUT',
            //         data:{
            //             completed:completed,
            //             _token:$("input[name=_token]").val()
            //         },
            //         success:function (response) {
            //             if(response == 1) {
            //                 var  nextid =checkbox.closest('td').next();
            //                 if(completed){
            //                     nextid.addClass('done');
            //                 } else {
            //                     nextid.removeClass('done');
            //                 }
            //                 countActiveTasks();
            //             }
            //         }
            //     });
            // }

            // function initIcheck() {
            //     $('input[type=checkbox]').iCheck({
            //         checkboxClass:'icheckbox_square-green',
            //         increaseArea:'20%'
            //     });

            //     $('#check_all').on('ifChecked',function(e){
            //         $('.check-item').iCheck('check');
            //     });

            //     $('#check_all').on('ifUnchecked',function(e){
            //         $('.check-item').iCheck('uncheck');
            //     });

            //     $('.check-item')
            //         .on('ifChecked',function (e) {
            //             var checkbox= $(this);
            //             markTheTask(checkbox);
            //         })
            //         .on('ifUnchecked',function (e) {
            //             var checkbox= $(this);
            //             markTheTask(checkbox);
            //         });
            // }

            // Change completed Or Not in manage Task
            // $(".filter-btn").click(function (e) {
            //     e.preventDefault();
            //     var id = this.id;
            //     $(this).addClass('active')
            //         .parent()
            //         .children()
            //         .not(e.target)
            //         .removeClass('active');
            //     if (id == 'all-tasks'){
            //             $('tr.task-item').show();
            //     } else if(id == 'active-tasks'){
            //         $('tr.task-item:has(td.done)').hide();
            //         $('tr.task-item:not(:has(td.done))').show();
            //     } else if(id == "completed-tasks"){
            //         $('tr.task-item:has(td.done)').show();
            //         $('tr.task-item:not(:has(td.done))').hide();
            //     }
            // });

        }());
    </script>
@endsection
