@extends('layouts.master')
@section('title','History of Purchase Requests')
@section('extra-css')
    <style>
        span.label{
            font-weight: 300 !important;
            font-size: 12px !important;
        }
    </style>
@endsection

@section('content')

<div id="page-wrapper">
    <div class="row">
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header" style="padding-left: 10px">
                    <div class="navbar-text navbar-brand-centered"><h4>Fresh Inventory | History</h4></div>
                </div>
            </div>
        </nav>
    </div>
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">History of Purchase Request(s)</div>
            <div class="panel-body">
                <div>
                    <table id="history_pr_table" class="table table-hover table-bordered table-responsive" style="width:100%"></table>
                </div>
            </div>
            <div class="panel-footer"></div>
        </div>
    </div>
</div>
@endsection

@section('extra-js')
<script>
    (function(){
        // DataTable Sorted Listing
        $('#history_pr_table').DataTable({
            "processing": true,
            "serverSide": true,
            "ajax": "/warehouse/fresh-inventory-history-data",
            "columnDefs": [ { //this prevents errors if the data is null
                "targets": "_all",
                "defaultContent": ""
            } ],
            "language": {
                "search": "Search Records: "
            },
            "order": [[0,'desc']],
            "columns": [
                {data: 'id', title: 'ID', orderable: true, searchable: true, 'className' : 'text-center', "width": "5%"},
                {data: 'batch_no', title: 'BATCH ID', orderable: true, searchable: true, 'className' : 'text-center', "width": "15%"},
                {data: 'product_id', title: 'PRODUCT ID', orderable: true, searchable: true, 'className' : 'text-center', "width": "10%"},
                {data: 'created_by', title: 'GENERATED BY', orderable: true, searchable: true, 'className' : 'text-center', "width": "15%"},
                {data: 'created_at', title: 'GENERATED AT', orderable: false, searchable: false, 'className' : 'text-center', "width": "15%"},
                {data: 'completed_at', title: 'SUBMITTED AT', orderable: false, searchable: false, 'className' : 'text-center', "width": "15%"},
                {data: 'completed_by', title: 'SUBMITTED BY', orderable: true, searchable: true, 'className' : 'text-center', "width": "15%"},
                {data: 'status', title: 'STATUS', orderable: true, searchable: true, 'className' : 'text-center', "width": "15%"},
                // {data: 'action', title: 'ACTION', orderable: false, searchable: false, 'className' : 'text-center'}
            ],
            "buttons": [
                'pdf'
            ]
        });
    }());
</script>
@endsection