<?php

class PushNotificationController extends BaseController
{
    public function __construct()
    {
        $this->beforeFilter('auth');
    }

    /**
     * Display a list of notification message
     * Data generated by getDatanotification() method via AJAX
     * @return View
     */
    public function getIndex()
    {
        return View::make('push.index');
    }

    /**
     * Form for adding new push notification
     * @return View
     */
    public function getCreate()
    {
        $parentCategory = PushNotificationCategory::where("activation",1)
                ->where("is_parent",1)
                ->get();
                
        $sound = DB::table('notification_voice_reference')
            ->where('activation',1)->get();
        
        return View::make('push.create')
                ->with("parentCategory",$parentCategory)
                ->with("sound",$sound);
    }

    /**
     * Display a list of device
     * Data generated by getDatadevice() method via AJAX
     * @return View
     */
    public function getDevice()
    {
        return View::make('push.device');
    }

    /**
     * Form for editing push notification
     * @return View
     */
    public function getEdit($id)
    {
        $message = PushMessage::findOrFail($id);

        return View::make('push.edit', ['notification' => $message]);
    }

    /**
     * Display a list of sent notification
     * @return View
     */
    public function getHistory()
    {
        return View::make('push.history');
    }

    /**
     * Display a list of queue
     * Data generated by getDataqueue() method via AJAX
     * @return View
     */
    public function getQueue()
    {
        return View::make('push.queue');
    }

    public function postDelete()
    {
        PushMessage::destroy(Input::get('id'));

        return Redirect::back();
    }

    /**
     * Put pending message-device pair back to queue
     */
    public function postResume()
    {
        $messageId = Input::get('id');
        $begin     = Input::get('begin');
        $message   = PushMessage::findOrFail($messageId);
        $devices   = Device::pushEnabled()->get();
        $sents     = array_pluck(PushQueue::sent($message->id)->get()->toArray(), 'device_id');

        $this->addQueue($message, $devices, $begin, $sents);

        $message->status = 'Processing';
        $message->save();

        return Redirect::back();
    }

    /**
     * Change message status to pending
     * Delete queuing message-device pair from queue
     * @return Redirect back
     */
    public function postStop()
    {
        $message = PushMessage::findOrFail(Input::get('id'));
        $sent    = PushQueue::sent($message->id)->count();

        if ($sent > 0) {
            $message->status = 'Stopped';
            $message->save();
        } else {
            $message->status = 'Pending';
            $message->save();
        }

        $queues = PushQueue::where('push_message_id', '=', $message->id)
            ->whereNull('sent_at')
            ->delete();

        return Redirect::back();
    }

    /**
     * Delete a queued notification
     */
    public function postDeleteQueue()
    {
        PushQueue::destroy(Input::get('id'));

        $inQueue = PushMessage::inQueue()->get();

        // Update message status to 'Completed' if no message in queue
        foreach ($inQueue as $message) {
            $queueCount = PushQueue::where('push_message_id', '=', $message->id)
                ->whereNull('sent_at')
                ->count();

            if ($queueCount == 0) {
                $message->status = 'Completed';
                $message->save();
            }
        }

        return Redirect::back();
    }

    /**
     * Update a push notification
     */
    public function postUpdate($id)
    {
        $data               = Input::only('message');
        $begin              = Input::get('begin');
        $recipient          = Input::get('recipient');
        $recipientUsernames = Input::get('recipient-usernames');
        $rule               = [
            'message'             => 'required|max:255',
            'recipient-usernames' => 'required|alpha_num',
        ];

        if (empty($begin)) {
            $begin = date('Y-m-d H:i:s');
        }

        if ($recipient == 'specify') {
            $usernames = explode(',', trim(str_replace(' ', '', $recipientUsernames)));

            if (count($usernames) == 0) {
                $usernames[0] = '-';
            }

            foreach ($usernames as $username) {
                $input = [
                    'message'             => Input::get('message'),
                    'recipient-usernames' => $username,
                ];

                $validator = Validator::make($input, $rule);

                if ($validator->fails()) {
                    $errors = $validator->messages();

                    return Redirect::back()->withInput()->withErrors($errors);
                }
            }

            $devices = Device::whereIn('username', $usernames)
                ->pushEnabled()
                ->get();
        } else {
            $devices = Device::pushEnabled()->get();
        }

        $message = PushMessage::findOrFail($id);
        $sents   = array_pluck(PushQueue::sent($message->id)->get()->toArray(), 'device_id');

        $this->addQueue($message, $devices, $begin, $sents);

        foreach ($data as $column => $value) {
            $message->$column = $value;
        }

        $message->status = 'Processing';
        $message->save();

        return Redirect::to('push');
    }

    /**
     * Process of storing new push notification
     * @param POST message  (string) Push notification message
     * @param POST begin    (string) Start sending date time
     */
    public function postStore()
    {
        try{
        // echo '<pre>';    
        // print_r(Input::all());
        // echo '</pre>';
        // die();
        $target_platform =0;
        set_time_limit(0);
        $notification_image = Input::file('filename_image');
        
        if($notification_image != ""){
            $file_ext = $notification_image->getClientOriginalExtension();
        }else{
            $file_ext = "";
        }
        
        $filename = '';
        $data               = Input::only('message');
        $begin              = Input::get('begin');
        $title              = Input::get('title');
        $recipient          = Input::get('recipient');
        $recipientUsernames = Input::get('recipient-usernames');
        $main_category      = Input::get('category');
        $sub_category       = Input::get('sub_category');
        $link_id            = Input::get('link_id');
        $target_platform    = Input::get('platform');
        $sound_type   = Input::get('sound_type');
       
        $main_category_code = '';
        $sub_category_code = '';
        
        $rule               = [
            'message'             => 'required|max:255',
            'recipient-usernames' => 'required',
        ];

        if (empty($begin)) {
            $begin = date('Y-m-d H:i:s');
        }

        if ($recipient == 'specify') {
            $usernames = explode(',', trim(str_replace(' ', '', $recipientUsernames)));

            if (count($usernames) == 0) {
                $usernames[0] = '-';
            }

            foreach ($usernames as $username) {
                $input = [
                    'message'             => Input::get('message'),
                    'recipient-usernames' => $username,
                ];

                $validator = Validator::make($input, $rule);

                if ($validator->fails()) {
                    $errors = $validator->messages();

                    return Redirect::back()->withInput()->withErrors($errors);
                }
            }

            $devices = Device::whereIn('username', $usernames)
                ->pushEnabled()
                ->get();
        } else {
            
            if($target_platform =='')
            {
              $target_platform = 0;  
            }
            // echo $target_platform.'x';
            //  die();
            switch ($target_platform) {
                case 1:
                    $devices = Device::where('os', '=', 'Android')->pushEnabled()->get();
                    break;
                case 2:
                    $devices = Device::where('os', '=', 'iOS')->pushEnabled()->get();
                    break;
                default:
                    $devices = Device::pushEnabled()->get();
                    break;
            }
        }
        // print_r($devices);
        //  die();
        $message = new PushMessage;
        $result  = $message->store($data);
        $result = true;
        if ($result === true) {
            
            if(Input::hasFile("filename_image")) {
            
                $file_ext = $notification_image->getClientOriginalExtension();
                $filename = rand(10,100)."_".date("ymdhis").'.'.$file_ext;
                $dest_path  = Config::get('constants.PUSH_NOTIFICATION_IMAGE_PATH');
                $upload_file_succ = Input::file('filename_image')->move($dest_path, $filename);
            
            }else{
                $filename = '';
            }
        
            //$this->addQueue($message, $devices, $begin);
            
            $message->filename_image = $filename;
            $message->title = $title;
            $message->link_id = $link_id;
            
            if($main_category != ""){
                $MainCategory  = PushNotificationCategory::find($main_category);
                $main_category_code = $MainCategory->code;
            }
            
            if($sub_category != ""){
                $SubCategory  = PushNotificationCategory::find($sub_category);
                $sub_category_code = $SubCategory->code;
            }
            
            if ($recipient == 'specify') {
                $message->target = 'SPECIFY';
            }else{
                $message->target = 'EVERYONE';
            }
            
            $message->main_category = $main_category_code;
            $message->sub_category = $sub_category_code;
            $message->target_platform = $target_platform;
            $message->sound_code = $sound_type;
            $message->status = 'Processing';
            $message->save();
            
            if ($recipient == 'specify') {
                $this->addQueue($message, $devices, $begin);
            }else{
                $this->addQueueStoreProc($message, $target_platform, $begin);
            }

            return Redirect::to('push');
        } else {
            return Redirect::back()->withInput()->withErrors($result);
        }
        
        }catch(exception $ex){
            echo $ex->getMessage();
        }
    }

    /**
     * Retrieve list of device in Datatables format
     * @return Datatables
     */
    public function getDatadevice()
    {
        return Datatables::of(Device::datatables())
            ->edit_column('os', function ($queue) {
                if ($queue->os != 'Android') {
                    switch ($queue->os) {
                        case 'iOS':
                            return 'iOS - iPhone';
                            break;
                        case 'iPad':
                            return 'iOS - iPad';
                            break;
                    }
                } else {
                    return $queue->os;
                }
            })
            ->edit_column('full_name', function ($device) {
                return empty($device->full_name) ? '-' : "{$device->full_name} ({$device->username})";
            })
            ->edit_column('push', function ($device) {
                return ($device->push) ? 'Enabled' : 'Disabled';
            })
            ->make();
    }
    
    public function anySubcategory()
    {   
        
        $main_category_id = Input::get("main_category_id");
        
        $SubCategory = PushNotificationCategory::where("parent_id",$main_category_id)
                ->where("activation",1)
                ->get();
        
        return $SubCategory;
        
    }

    /**
     * Retrieve list of sent notification message in Datatables format
     * @return Datatables
     */
    public function getDatahistory()
    {
        return Datatables::of(PushQueue::datatablesHistory())
            ->edit_column('full_name', function ($queue) {
                return empty($queue->full_name) ? '-' : $queue->full_name;
            })
            ->edit_column('os', function ($queue) {
                if ($queue->os != 'Android') {
                    switch ($queue->os) {
                        case 'iOS':
                            return 'iOS - iPhone';
                            break;
                        case 'iPad':
                            return 'iOS - iPad';
                            break;
                    }
                } else {
                    return $queue->os;
                }
            })
            ->make();
    }

    /**
     * Retrieve list of notification message in Datatables format
     * @return Datatables
     */
    public function getDatanotification()
    {
        return Datatables::of(PushMessage::datatables())
            ->edit_column('status', function ($notification) {
                if ($notification->status == 'Processing') {
                    $total = PushQueue::where('push_message_id', '=', $notification->id)->count();
                    $sent  = PushQueue::sent($notification->id)->count();

                    return $notification->status . " ({$sent}/{$total})";
                } else {
                    return $notification->status;
                }
            })
            ->add_column('action', function ($notification) {
                if ($notification->status == 'Pending') {
                    return '<a class="btn btn-primary btn-sm" href="' . url("push/edit/{$notification->id}") . '"><i class="fa fa-pencil"></i></a> ' .
                    '<a class="btn btn-danger btn-sm" data-toggle="modal" data-target="#deleteModal" data-value="' . $notification->id . '" href="#"><i class="fa fa-close"></i></a>';
                }
                if ($notification->status == 'Processing') {
                    return '<a class="btn btn-danger btn-sm" data-toggle="modal" data-target="#stopModal" data-value="' . $notification->id . '" href="#"><i class="fa fa-ban"></i></a>';
                }
            })
            ->make();
    }

    /**
     * Retrieve list of queue in Datatables format
     * @return Datatables
     */
    public function getDataqueue()
    {
        return Datatables::of(PushQueue::datatables())
            ->edit_column('os', function ($queue) {
                if ($queue->os != 'Android') {
                    switch ($queue->os) {
                        case 'iOS':
                            return 'iOS - iPhone';
                            break;
                        case 'iPad':
                            return 'iOS - iPad';
                            break;
                    }
                } else {
                    return $queue->os;
                }
            })
            ->edit_column('full_name', function ($queue) {
                return empty($queue->full_name) ? '-' : $queue->full_name;
            })
            ->add_column('action', function ($queue) {
                return '<a class="btn btn-danger btn-sm" data-toggle="modal" data-target="#deleteModal" data-value="' . $queue->id . '" href="#"><i class="fa fa-remove"></i></a>';
            })
            ->make();
    }

    /**
     * Add a single record into queue
     * @return void
     */
    private function addQueue($message, $devices, $begin, array $ignore = [])
    {
        foreach ($devices as $device) {
            if (!in_array($device->id, $ignore)) {
                PushQueue::create([
                    'push_message_id' => $message->id,
                    'device_id'       => $device->id,
                    'begin'           => $begin,
                ]);
            }
        }
    }
    
    // Pass to store procedure 
    private function addQueueStoreProc($message, $type, $begin)
    {
        switch ($type) {
           
            case '1':
                DB::statement("CALL push_queue_android('$begin','$message->id')");
                break;
            case '2':
                DB::statement("CALL push_queue_ios('$begin','$message->id')");
                break;
            default:
                DB::statement("CALL push_queue('$begin','$message->id')");
                break;
         
        }
        
        return true;
        
    }
}
